language: python
sudo : false
python:
  - "3.4"

matrix:
  include:
    - env env: DISTRIB="ubuntu" PYTHON_VERSION="3.4"
      addons:
        apt: 
          sources:
          packages:
              - python-numpy
              - python-zmq
              - python-qt4

if [[ "$DISTRIB" == "ubuntu" ]]; then
    deactivate
    virtualenv --system-site-packages testvenv
    source testvenv/bin/activate
    pip install pytest
    cd pyacq
    python setup.py develop
fi

script:
  py.test
