language: python
sudo : false
python:
  - 3.4

virtualenv:
    system_site_packages: true
  
matrix:
  include:
    - env env: DISTRIB="ubuntu" PYTHON_VERSION="3.4"
      addons:
        apt: 
          sources:
          packages:
              - python-numpy
              - python-zmq
              - python-qt4

install:

    - if [[ "$DISTRIB" == "ubuntu" ]]; then
        pip install pytest;
      fi;


script:
  py.test


