import os

ex_path = os.path.join('..', '..', 'examples')

index = """
.. Do not edit!
.. Automatically generated by pyacq/doc/examples/gen.py

Examples
========

Contents:

.. toctree::
   :maxdepth: 2

"""

template = """
{title}
{line}

.. literalinclude:: {file}
   :language: python
"""

examples = [f for f in os.listdir(ex_path) if f.endswith('.py')]
for example in examples:
    exname = example[:-3]
    expath = os.path.join(ex_path, example)
    index = index + "   %s\n" % exname
    
    excode = open(expath, 'rb').readlines()
    title = exname
    for i, line in enumerate(excode):
        if line.strip() == '"""':
            title = excode[i+1].strip()
            break
    print("%s%s  --  %s" % (example, " "*(30-len(example)), title))
    rst = template.format(title=title, line="="*len(title), file=expath)
    open(exname+'.rst', 'wb').write(rst.encode())


open('index.rst', 'wb').write(index.encode())